version: '3'

services:
    restoran-postgres:
        image: postgres:14.2-alpine
        container_name: restoran-postgres-14.2
        volumes:
            - postgres:/var/lib/postgresql/data
        command:
            "postgres -c 'max_connections=500'"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "127.0.0.1:5433:5432"
    restoran-web:
        build: .
        container_name: restoran-web
        command: "./bin/rails server"
        environment:
            - RAILS_ENV=${RAILS_ENV}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        volumes:
            - web:/rails/storage
        depends_on:
            - restoran-postgres
        ports:
            - "127.0.0.1:4000:4000"

volumes:
    web: {}
    postgres: {}